apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
    patch: |-
      - op: add
        path: /spec/ingress/-
        value:
          ports:
            - port: 15008
              protocol: TCP
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      - op: add
        path: /data
        value:
          server.insecure: "true"
