apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: argocd
  namespace: external-dns
spec:
  endpoints:
    - dnsName: argocd.alexmickelson.guru
      recordType: A
      targets:
        - 100.94.176.125
