services:
  ts-ingress:
    image: tailscale/tailscale:latest
    container_name: dns-tailscale
    hostname: home-dns
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/config.json
      # - TS_AUTHKEY=
    volumes:
      - tailscale-data:/var/lib/tailscale
      - ./ts-serve-config.json:/config/config.json
      - /dev/net/tun:/dev/net/tun
    cap_add:
    - net_admin
    - sys_module

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
  #   # ports:
  #     # - "0.0.0.0:53:53/tcp"
  #     # - "0.0.0.0:53:53/udp"
  #     # - "127.0.0.1:53:53/tcp"
  #     # - "127.0.0.1:53:53/udp"
  #     # - "100.122.128.107:53:53/tcp"
  #     # - "100.122.128.107:53:53/udp"
  # #     # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
  #     # - "8580:80"
  #   environment:
  #     TZ: 'America/Denver'
  #     # WEBPASSWORD: 'set a secure password here or it will be random'
  #   volumes:
  #     - '/data/pihole/etc-pihole:/etc/pihole'
  #     - '/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
  #   #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #   # cap_add:
  #   #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
  #   restart: unless-stopped
  #   network_mode: service:ts-ingress


  adguardhome:
    image: adguard/adguardhome
    container_name: dns-adguardhome
    network_mode: service:ts-ingress
    restart: unless-stopped
    volumes:
      - /data/adguard/conf:/opt/adguardhome/conf
      - /data/adguard/work:/opt/adguardhome/work
    depends_on:
      - ts-ingress

volumes:
  tailscale-data: