apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ttyd
  namespace: external-dns
spec:
  endpoints:
    - dnsName: shell.alexmickelson.guru
      recordType: CNAME
      targets:
        - pangolin.alexmickelson.guru
