apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  namespace: nextcloud
  labels:
    app: nextcloud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          args:
            [
              "--transaction-isolation=READ-COMMITTED",
              "--log-bin=binlog",
              "--binlog-format=ROW",
            ]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: klsdnofinsodkflksen34tesrg
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: slkdnflksnelkfnsdweoinv
          volumeMounts:
            - name: nextcloud-db-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: mysql
      volumes:
        - name: nextcloud-db-data
          hostPath:
            path: /data/nextcloud-db
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
  namespace: nextcloud
  labels:
    app: nextcloud-db
spec:
  selector:
    app: nextcloud-db
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
