services:
  db:
    image: metabrainz/musicbrainz-docker-db:16-build0
    container_name: musicbrainz-db
    restart: unless-stopped
    command: postgres -c "shared_buffers=2048MB"
    environment:
      POSTGRES_USER: musicbrainz
      POSTGRES_PASSWORD: musicbrainz
      POSTGRES_DB: musicbrainz_db
    shm_size: "2GB"
    volumes:
      - /data/musicbrainz/db:/var/lib/postgresql/data

  redis:
    image: redis:3-alpine
    container_name: musicbrainz-redis
    restart: unless-stopped

  mq:
    image: rabbitmq:3-alpine
    container_name: musicbrainz-mq
    hostname: "mq"
    restart: unless-stopped
    volumes:
      - /data/musicbrainz/rabbitmq:/var/lib/rabbitmq

  musicbrainz:
    image: metabrainz/musicbrainz-docker-musicbrainz:v-2025-10-13.0-build1
    container_name: musicbrainz-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: musicbrainz
      POSTGRES_PASSWORD: musicbrainz
      POSTGRES_DB: musicbrainz_db
      MUSICBRAINZ_WEB_SERVER_HOST: 0.0.0.0
      MUSICBRAINZ_WEB_SERVER_PORT: 5000
      REDIS_SERVER: redis:6379
      RABBITMQ_HOST: mq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: /
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      # Replication
      REPLICATION_TYPE: RT_SLAVE
      REPLICATION_ACCESS_TOKEN: ${MUSICBRAINZ_TOKEN}
    depends_on:
      - db
      - redis
      - mq
    volumes:
      - /data/musicbrainz/dbdump:/media/dbdump