name: Apply Kuberentes Configs
on: [push, workflow_dispatch]
jobs:
  update-repo:
    uses: ./.gitea/workflows/update-repo.yml
  update-infrastructure:
    runs-on: home-server
    needs: update-repo-folder
    steps:
      - name: update home server containers
        env:
          KUBECONFIG: /home/gitea-runner/.kube/config
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          HOMEASSISTANT_TOKEN: ${{ secrets.HOMEASSISTANT_TOKEN }}
          GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
          CLOUDFLARE_CONFIG: ${{ secrets.CLOUDFLARE_CONFIG }}
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        working-directory: /home/gitea-runner/infrastructure
        run: |
          # kubectl apply -f kubernetes/ingress
          kubectl apply -f kubernetes/proxy-ingress

          kubectl annotate ingressclass nginx \
            ingressclass.kubernetes.io/is-default-class="true" --overwrite
