name: Apply Kuberentes Configs
on: [push, workflow_dispatch]
jobs:
  update-repo:
    uses: ./.gitea/workflows/update-repo.yml
    runs-on: home-server
  update-infrastructure:
    runs-on: home-server
    needs: update-repo-folder
    steps:
      - name: update home server containers
        env:
          KUBECONFIG: /home/gitea-runner/.kube/config
        working-directory: /home/gitea-runner/infrastructure
        run: |
          kubectl apply -f kubernetes/proxy-ingress

          kubectl annotate ingressclass nginx \
            ingressclass.kubernetes.io/is-default-class="true" --overwrite

      - name: audiobookshelf
        env:
          KUBECONFIG: /home/gitea-runner/.kube/config
        working-directory: /home/gitea-runner/infrastructure
        run: |
          kubectl apply -f kubernetes/audiobookshelf/

      - name: home assistant
        env:
          KUBECONFIG: /home/gitea-runner/.kube/config
        working-directory: /home/gitea-runner/infrastructure
        run: |
          kubectl apply -f kubernetes/homeassistant/

      - name: copilot
        env:
          KUBECONFIG: /home/gitea-runner/.kube/config
        working-directory: /home/gitea-runner/infrastructure
        run: |
          kubectl create secret generic copilot-secret \
            -n copilot \
            --from-literal=token=${{ secrets.COPILOT_SECRET }} \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl apply -f kubernetes/copilot/
