name: ZFS Backup
runs-on: home-server
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:
jobs:
  update-infrastructure:
    steps:
      - name: run syncoid
        run: |
          zpool status
          echo ""
          zfs list
          echo ""
          syncoid \
            --recursive \
            --no-privilege-elevation \
              data-ssd/data \
              backup/data

          syncoid \
            --recursive \
            --no-privilege-elevation \
              data-ssd/media \
              backup/media