name: Libation
on:
  schedule:
    - cron: '0 6,12,18,0 * * *'
  workflow_dispatch: 

jobs:
  update-repo:
    uses: ./.gitea/workflows/update-repo.yml
    runs-on: home-server
  sync-audiobooks:
    runs-on: [home-server]
    steps:
      - name: Run Libation sync
        working-directory: /home/gitea-runner/infrastructure/home-server/libation
        run: |
          echo "Starting Libation audiobook sync at $(date)"
          docker compose pull -q
          docker compose run --rm libation
          echo "Libation sync completed at $(date)"
