name: Libation
on:
  schedule:
    - cron: '0 6,12,18,0 * * *'
  workflow_dispatch: 

jobs:
  update-repo:
    uses: ./.gitea/workflows/update-repo.yml
    runs-on: home-server
  sync-audiobooks:
    runs-on: [home-server]
    steps:
      - name: Run Libation sync
        working-directory: /home/gitea-runner/infrastructure/home-server/libation
        run: |
          echo "Starting Libation audiobook sync at $(date)"
          docker compose pull -q
          docker compose run --rm libation
          echo "Libation sync completed at $(date)"

  notify-on-failure:
    runs-on: home-server
    needs: sync-audiobooks
    if: failure()
    uses: ./.gitea/workflows/notify-ntfy.yml
    secrets:
      NTFY_CHANNEL: ${{ secrets.NTFY_CHANNEL }}
    with:
      title: "Libation Sync Failed"
      message: |
        Failed to sync audiobooks with Libation
        Workflow: ${{ gitea.workflow }}
        Repository: ${{ gitea.repository }}
        Job: sync-audiobooks
        Status: ${{ needs.sync-audiobooks.result }}
      action_url: "https://git.alexmickelson.guru/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }}"
      priority: "high"
      tags: "rotating_light,audiobooks"
