name: Notify NTFY
on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      message:
        required: true
        type: string
      priority:
        required: false
        type: string
        default: "default"
      tags:
        required: false
        type: string
        default: "warning"
    secrets:
      NTFY_CHANNEL:
        required: true

jobs:
  send-notification:
    runs-on: [home-server]
    steps:
      - name: Send ntfy notification
        working-directory: /home/gitea-runner
        run: |
          set -e
          cat <<EOF | curl -f -H "Title: ${{ inputs.title }}" \
               -H "Priority: ${{ inputs.priority }}" \
               -H "Tags: ${{ inputs.tags }}" \
               --data-binary "@-" \
               "https://ntfy.sh/${{ secrets.NTFY_CHANNEL }}"
          ${{ inputs.message }}
          EOF
