name: Manage Jellyfin Playlists
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-repo:
    uses: ./.gitea/workflows/update-repo.yml
    runs-on: home-server
  run-python:
    runs-on: home-server
    steps:
    - name: Run Python script
      env:
        JELLYFIN_USER: ${{ secrets.JELLYFIN_USER }}
        JELLYFIN_PASSWORD: ${{ secrets.JELLYFIN_PASSWORD }}
      working-directory: /home/gitea-runner/infrastructure
      run: |
        echo "$JELLYFIN_USER $JELLYFIN_PASSWORD" > /home/gitea-runner/jellyfin_credentials.txt
        docker build -t jellyfin_management -f jellyfin/Dockerfile .
        docker run --rm \
        -e JELLYFIN_USER=$JELLYFIN_USER \
        -e JELLYFIN_PASSWORD=$JELLYFIN_PASSWORD \
          jellyfin_management \
            -m jellyfin.update_all_songs_playlist
        docker run --rm \
        -e JELLYFIN_USER=$JELLYFIN_USER \
        -e JELLYFIN_PASSWORD=$JELLYFIN_PASSWORD \
          jellyfin_management \
            -m jellyfin.update_unindexed

  notify-on-failure:
    runs-on: home-server
    needs: run-python
    if: failure()
    uses: ./.gitea/workflows/notify-ntfy.yml
    secrets:
      NTFY_CHANNEL: ${{ secrets.NTFY_CHANNEL }}
    with:
      title: "Jellyfin Playlist Update Failed"
      message: |
        Failed to update Jellyfin playlists
      action_url: "https://git.alexmickelson.guru/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }}"
      priority: "high"
      tags: "rotating_light,jellyfin"
