apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://git.alexmickelson.guru/alex/infrastructure.git
      targetRevision: HEAD
      path: kubernetes/argocd
    - repoURL: https://git.alexmickelson.guru/alex/infrastructure.git
      targetRevision: HEAD
      path: kubernetes/argocd-self
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-extras
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.alexmickelson.guru/alex/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/argocd-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
