apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autokuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.alexmickelson.guru/alex/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/autokuma
  destination:
    server: https://kubernetes.default.svc
    namespace: uptimekuma
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
