apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec-resources
  namespace: argocd
  annotations:
    # External Secrets and Vault are installed at waves 11 and 10 respectively.
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://git.alexmickelson.guru/alex/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/crowdsec
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
