apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-extras
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.alexmickelson.guru/alex/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/tailscale-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
