apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: immich
  namespace: external-dns
spec:
  endpoints:
    - dnsName: photos.alexmickelson.guru
      recordType: CNAME
      targets:
        - igateway.alexmickelson.guru
