services:
  many_mcp:
    container_name: many_mcp
    build:
      context: .
      dockerfile: playwright.Dockerfile
    # restart: always
    ports:
      - 3901:3901

  playwright_novnc:
    build:
      context: .
      dockerfile: novnc.Dockerfile
    container_name: playwrite_novnc
    ports:
      - "3903:3903"
    depends_on:
      - many_mcp
    # restart: always
    command: >
      websockify --web=/opt/novnc --wrap-mode=ignore 3903 many_mcp:5900