apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/grafana-community/helm-charts
      chart: grafana
      targetRevision: 12.8.0
      helm:
        releaseName: grafana
        values: |
          persistence:
            enabled: false
          extraVolumes:
            - name: grafana-data
              hostPath:
                path: /data/grafana-kube
                type: DirectoryOrCreate
          extraVolumeMounts:
            - name: grafana-data
              mountPath: /data/grafana-kube
          grafana.ini:
            paths:
              data: /data/grafana-kube
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: Prometheus
                  uid: prometheus
                  type: prometheus
                  access: proxy
                  url: http://prometheus-server.monitoring.svc.cluster.local
                  isDefault: true
                  editable: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
    - repoURL: https://git.alexmickelson.guru/alex/infrastructure.git
      targetRevision: HEAD
      path: kubernetes/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
