apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
  namespace: minecraft
data:
  serve-config.json: |
    {
      "TCP": {
        "25565": {
          "TCPForward": "minecraft-svc.minecraft.svc.cluster.local:25565"
        },
        "2222": {
          "TCPForward": "minecraft-svc.minecraft.svc.cluster.local:2222"
        },
        "8085": {
          "TCPForward": "minecraft-svc.minecraft.svc.cluster.local:8085"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-tailscale
  namespace: minecraft
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-tailscale
  template:
    metadata:
      labels:
        app: minecraft-tailscale
    spec:
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest@sha256:f15d5d3f4a68773a853180b72496f70ba614b64de0878c43fe3da39fe0afba47
        env:
        - name: TS_STATE_DIR
          value: "/var/lib/tailscale"
        - name: TS_KUBE_SECRET
          value: ""
        - name: TS_AUTHKEY
          value: "tskey-auth-REPLACE_ME"
        - name: TS_HOSTNAME
          value: "minecraft"
        - name: TS_SERVE_CONFIG
          value: "/etc/tailscale/serve-config.json"
        volumeMounts:
        - name: tailscale-data
          mountPath: /var/lib/tailscale
        - name: dev-tun
          mountPath: /dev/net/tun
        - name: serve-config
          mountPath: /etc/tailscale
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
      volumes:
      - name: tailscale-data
        hostPath:
          path: /data/minecraft/tailscale
          type: DirectoryOrCreate
      - name: dev-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      - name: serve-config
        configMap:
          name: tailscale-serve-config
