apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: minecraft-create-evolution
        image: itzg/minecraft-server:java21@sha256:6711f4310d536aeac9dc16baa387b3957ed903890e21ed0b766019439be5c12b
        stdin: true
        tty: true
        env:
        - name: EULA
          value: "true"
        - name: TYPE
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "create-evolution-renewed"
        - name: CF_FILE_ID
          value: "9026087"
        - name: MEMORY
          value: "8G"
        - name: SERVER_PORT
          value: "25565"
        - name: RCON_PORT
          value: "25575"
        - name: CF_OVERRIDES_EXCLUSIONS
          value: |
            shaderpacks/**
            resourcepacks/**
        volumeMounts:
        - name: create-evolution-data
          mountPath: /data
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 30"]
        resources:
          requests:
            memory: "8Gi"
          limits:
            memory: "10Gi"
      volumes:
      - name: create-evolution-data
        hostPath:
          path: /data/minecraft/create-evolution-data
          type: DirectoryOrCreate
