apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: forgejo
  name: forgejo-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: forgejo-db
  template:
    metadata:
      labels:
        app: forgejo-db
    spec:
      containers:
        - name: postgres
          image: postgres:18@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "forgejo"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: forgejo-db-secrets
                  key: credentials.json
            - name: POSTGRES_DB
              value: "forgejo"
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
      volumes:
        - name: postgres-data
          hostPath:
            path: /data/forgejo/postgres
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-db-svc
  namespace: forgejo
  labels:
    app: forgejo-db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: forgejo-db
  type: ClusterIP
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-external-secret # external secret name
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: forgejo-db-secrets # secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: forgejo
        property: POSTGRESS_PASSWORD
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
