apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.alexmickelson.guru/alex/infrastructure
    # repoURL: https://github.com/alexmickelson/infrastructure
    targetRevision: main
    path: kubernetes/audiobookshelf
  destination:
    server: https://kubernetes.default.svc
    namespace: audiobookshelf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

