apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptime-kuma-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: uptime-kuma-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: uptime-kuma
        property: username
    - secretKey: password
      remoteRef:
        key: uptime-kuma
        property: password
