apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-kuma-monitors
data:
  gateway-ready.toml: |
    type = "http"
    name = "Istio main gateway readiness"
    url = "http://main-gateway-istio.istio-ingress.svc.cluster.local:15021/healthz/ready"
    accepted_statuscodes = "200-299"
    interval = 30
    timeout = 10
    max_retries = 3
    retry_interval = 20
  homepage-public.toml: |
    type = "http"
    name = "Homepage (public)"
    url = "https://home.alexmickelson.guru"
    accepted_statuscodes = "200-399"
    interval = 60
    timeout = 10
    max_retries = 3
    retry_interval = 20
    expiry_notification = true
  homepage-service.toml: |
    type = "http"
    name = "Homepage (service)"
    url = "http://homepage.homepage.svc.cluster.local:3000"
    accepted_statuscodes = "200-299"
    interval = 60
    timeout = 10
    max_retries = 3
    retry_interval = 20
  forgejo-public.toml: |
    type = "http"
    name = "Forgejo (public)"
    url = "https://forgejo.alexmickelson.guru"
    accepted_statuscodes = "200-399"
    interval = 60
    timeout = 10
    max_retries = 3
    retry_interval = 20
    expiry_notification = true
  nextcloud-public.toml: |
    type = "http"
    name = "Nextcloud (public)"
    url = "https://next.alexmickelson.guru"
    accepted_statuscodes = "200-399"
    interval = 60
    timeout = 10
    max_retries = 3
    retry_interval = 20
    expiry_notification = true
  prometheus-public.toml: |
    type = "http"
    name = "Prometheus (public)"
    url = "https://prometheus.alexmickelson.guru"
    accepted_statuscodes = "200-399"
    interval = 60
    timeout = 10
    max_retries = 3
    retry_interval = 20
    expiry_notification = true
  jellyfin-public.toml: |
    type = "http"
    name = "Jellyfin (public)"
    url = "https://jelly-pub.alexmickelson.guru"
    accepted_statuscodes = "200-399"
    interval = 60
    timeout = 10
    max_retries = 3
    retry_interval = 20
    expiry_notification = true
