version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=45.79.102.212
      - WG_DEFAULT_ADDRESS=10.11.0.x
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_DNS=45.79.102.212
      # - WG_PORT=51820
    env_file:
      - ./wg-easy.env
    image: weejewel/wg-easy
    container_name: wireguard-web
    volumes:
      - /data/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default:
      proxy:

networks:
  default:

  proxy:
    external: true