version: '3'
services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - esphome-data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    # network_mode: service:ts-ingress
    environment:
      - USERNAME=alex
      - PASSWORD=alex

  # ts-ingress:
  #   image: tailscale/tailscale:latest
  #   container_name: ts-ingress
  #   hostname: esphomehttps://tailscale.com/blog/docker-tailscale-guide
  #   env_file:
  #     - .env
  #   environment:
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_SERVE_CONFIG=/config/esphome.json
  #   volumes:
  #     - tailscale-data:/var/lib/tailscale
  #     - ./ts-serve-config.json:/config/esphome.json
  #     - /dev/net/tun:/dev/net/tun
  #   cap_add:
  #   - net_admin
  #   - sys_module
volumes:
  tailscale-data:
  esphome-data: