apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
  namespace: monitoring
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway
      namespace: envoy-gateway-ingress
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: pangolin-gateway
      namespace: istio-ingress
  hostnames:
    - kiali.alexmickelson.guru
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: kiali
          port: 20001
          weight: 1
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kiali
  namespace: external-dns
spec:
  endpoints:
    - dnsName: kiali.alexmickelson.guru
      recordType: CNAME
      targets:
        - egateway.alexmickelson.guru
