
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /data/homepage:/app/config
      # - ./config/bookmarks.yaml:/app/config/bookmarks.yaml
      # - ./config/custom.css:/app/config/custom.css
      # - ./config/custom.js:/app/config/custom.js
      # - ./config/docker.yaml:/app/config/docker.yaml
      # - ./config/kubernetes.yaml:/app/config/kubernetes.yaml
      # - ./config/services.yaml:/app/config/services.yaml
      # - ./config/settings.yaml:/app/config/settings.yaml
      # - ./config/widgets.yaml:/app/config/widgets.yaml
      - /var/run/docker.sock:/var/run/docker.sock # pass local proxy
    ports:
      - 3001:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=server.alexmickelson.guru
    restart: unless-stopped