name: ZFS Backup
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:
jobs:
  update-infrastructure:
    runs-on: [self-hosted, home-server]
    steps:
      - name: run syncoid
        run: |
          zpool status
          echo ""
          zfs list
          echo ""
          syncoid \
            --recursive \
            --no-privilege-elevation \
              data-ssd/data \
              backup/data

          syncoid \
            --recursive \
            --no-privilege-elevation \
              data-ssd/media \
              backup/media
    # steps:
    #   - name: run syncoid
    #     run: |
    #       zpool status
    #       echo ""
    #       zfs list
    #       echo ""
    #       syncoid \
    #         --recursive \
    #         --no-privilege-elevation \
    #         --no-rollback \
    #           data-ssd/data \
    #           backup/data

    #       syncoid \
    #         --recursive \
    #         --no-privilege-elevation \
    #         --no-rollback \
    #           data-ssd/media \
    #           backup/media