name: Beets
on:
  schedule:
    # Run 4 times a day: 6am, 12pm, 6pm, 12am UTC
    - cron: '0 6,12,18,0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-audiobooks:
    runs-on: [home-server]
    steps:
      - name: Run Beets sync
        working-directory: /home/github/infrastructure/infrastructure/home-server/beets
        run: |
          echo "Starting Beets audiobook sync at $(date)"
          docker compose pull 
          docker compose up -d
          docker exec -it -u 1000 beets bash -c "beet -v import -i -q /managed/*"
          docker compose down
          echo "Beets sync completed"
