name: Deploy Discord Bot
on:
  workflow_dispatch:
jobs:
  run-python:
    runs-on: [self-hosted, home-server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy bot
        env:
          DISCORD_SECRET: ${{ secrets.DISCORD_SECRET }}
        run: |
          cd discord-bot
          ./run.sh
