name: Libation
on:
  schedule:
    # Run 4 times a day: 6am, 12pm, 6pm, 12am UTC
    - cron: '0 6,12,18,0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-audiobooks:
    runs-on: [home-server]
    steps:
      - name: Run Libation sync
        working-directory: /home/github/infrastructure/infrastructure/home-server/libation
        run: |
          echo "Starting Libation audiobook sync at $(date)"
          docker compose pull -q
          docker compose run --rm libation
          echo "Libation sync completed at $(date)"
