services:
  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:v2
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /data/silverbullet:/space
    network_mode: service:ts-ingress
  
  ts-ingress:
    image: tailscale/tailscale:latest
    container_name: notes-tailscale
    hostname: notes
    restart: unless-stopped
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/config.json
    env_file:
      - ./.env
    volumes:
      - /data/tailscale/notes-proxy:/var/lib/tailscale
      - ./ts-serve-config.json:/config/config.json
      - /dev/net/tun:/dev/net/tun
    cap_add:
    - net_admin
    - sys_module